const AuthActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SET_TO_LOGGED_IN: 'SET_TO_LOGGED_IN',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

const UsersActionTypes = {
  GET_ALL_USERS: 'GET_ALL_USERS',
};

export {
  AuthActionTypes,
  UsersActionTypes,
};
