const UsersActionTypes = {
  GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',
  SORT_USERS: 'SORT_USERS',
  FILTER_USERS_BY_GRADE: 'FILTER_USERS_BY_GRADE',
  FILTER_USERS_BY_FULL_NAME: 'FILTER_USERS_BY_FULL_NAME',
  FILTER_USERS_BY_GENDER: 'FILTER_USERS_BY_GENDER',
};

export default UsersActionTypes;

