const CardsActionTypes = {
  GET_ALL_CARDS_REQUEST: 'GET_ALL_CARDS_REQUEST',
  GET_ALL_CARDS_SUCCESS: 'GET_ALL_CARDS_SUCCESS',
  GET_ALL_CARDS_FAILURE: 'GET_ALL_CARDS_FAILURE',
  SORT_CARDS: 'SORT_CARDS',
};

export default CardsActionTypes;

