const AuthActionTypes = {
  AUTH_FLOW_START: 'AUTH_FLOW_START',
  GOOGLE_LOGIN_REQUEST: 'GOOGLE_LOGIN_REQUEST',
  EMAIL_AND_PASSWORD_LOGIN_REQUEST: 'EMAIL_AND_PASSWORD_LOGIN_REQUEST',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SET_TO_LOGGED_IN: 'SET_TO_LOGGED_IN',
};

export default AuthActionTypes;
